# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Header
language: r
sudo: false
cache: packages
warnings_are_errors: true

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - MAKEFLAGS="-j 2"

# Linux
addons:
  apt:
    packages:
      - libmagick++-dev
      - libssh2-1-dev

# Matrix: 3x Linux, 1x OS X
matrix:
  include:
    - r: release
      env:
        - DEPLOY_PAGES=true
      r_github_packages:
        - hadley/pkgdown
        - krlmlr/travis@develop
      r_packages:
        - covr
        - roxygen2
    - r: oldrel
    - r: devel
    - os: osx
      osx_image: xcode7.2
      r: release
      latex: false

#r_packages
r_packages:
  - covr

#notifications
notifications:
  email:
    on_success: change
    on_failure: change

#after_success (deploy to gh-pages and run covr)
after_success:
  - scripts/deploy-pages.sh
  - R -e 'covr::codecov()'

# Custom parts:

#r_github_packages (also need to add to the matrix definition above)

#r_packages (need to copy packages included above, and add to the matrix definition)

#env (need to copy settings from above)

# services

#before_install

# before_script
